# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
executors:
  ruby:
    docker:
      - image: ruby:2.5
    working_directory: ~/hyrax
    environment:
      BUNDLE_PATH: ~/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

jobs:
  bundle:
    executor: ruby
    steps:
    - restore_cache:
        keys:
        - source-v1-{{ .Branch }}-{{ .Revision }}
        - source-v1-{{ .Branch }}-
        - source-v1-

    - checkout

    - run:
        name: Install dependencies
        command: bundle check || bundle install

    - save_cache:
        key: source-v1-{{ .Branch }}-{{ .Revision }}
        paths:
        - ".git"
        - ~/bundle

    - persist_to_workspace:
        root: ~/
        paths:
        - hyrax/*
        - hyrax/**/*
        - bundle/*
        - bundle/**/*

  lint:
    executor: ruby
    steps:
    - attach_workspace:
        at: ~/

    - run:
        name: Call Rubocop
        command: bundle exec rubocop

  build:
    docker:
    - image: circleci/ruby:2.5-node-browsers
    - image: circleci/redis:4
    - image: ualbertalib/docker-fcrepo4:4.7
      environment:
        CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
    - image: solr:7-alpine
      command: bin/solr -cloud -noprompt -f -p 8985

    working_directory: ~/hyrax

    environment:
      BUNDLE_PATH: ~/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RACK_ENV: test
      FCREPO_TEST_PORT: 8080/fcrepo
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      COVERALLS_PARALLEL: true

    steps:
    - attach_workspace:
        at: ~/

    - run:
        name: Generate test app
        command: |
          bundle exec rails new ~/test_app -m template.rb
          cd ~/test_app

    - run:
        name: Setup Gemfile dependencies
        command: |
          sed -i -- "s/gem 'sqlite3'/gem 'sqlite3', '< 1.4.0'/g" ~/test_app/Gemfile
          sed -i -- "s/gem 'hyrax', .*/gem 'hyrax', path: '..\/hyrax'/g" ~/test_app/Gemfile

    - run:
        name: Install app dependencies
        command: |
          cd ~/test_app
          bundle install --path ./vendor/bundle --binstubs ./vendor/bin

    - persist_to_workspace:
        root: ~/
        paths:
        - hyrax/*
        - hyrax/**/*
        - bundle/*
        - bundle/**/*
        - test_app/*
        - test_app/**/*

  test:
    docker:
    - image: circleci/ruby:2.5-node-browsers
    - image: circleci/redis:4
    - image: ualbertalib/docker-fcrepo4:4.7
      environment:
        CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
    - image: solr:7-alpine
      command: bin/solr -cloud -noprompt -f -p 8985

    working_directory: ~/hyrax
    parallelism: 4

    environment:
      BUNDLE_PATH: ~/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RACK_ENV: test
      FCREPO_TEST_PORT: 8080/fcrepo
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      COVERALLS_PARALLEL: true

    steps:
    - attach_workspace:
        at: ~/

    - run:
        name: Load config into SolrCloud
        command: |
          cd ~/test_app/solr/config
          zip -1 -r solr_hyrax_config.zip ./*
          curl -H "Content-type:application/octet-stream" --data-binary @solr_hyrax_config.zip "http://localhost:8985/solr/admin/configs?action=UPLOAD&name=hyrax"
          curl -H 'Content-type: application/json' http://localhost:8985/api/collections/ -d '{create: {name: hydra-test, config: hyrax, numShards: 1}}'

    - run:
        name: Run rspec in parallel
        command: |
          mkdir /tmp/test-results
          bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

workflows:
  version: 2
  ci:
    jobs:
      - bundle
      - lint:
          requires:
            - bundle
      - build:
          requires:
            - bundle
      - test:
          requires:
            - build
            - lint
